!=======================================================================
! Generated by  : PSCAD v4.5.0.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_XPI     ! 'Proportional-Integral Controller /w Interpolation'
!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, CLK, IT_2
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, S2a
      REAL     RT_11, RT_12, RT_13, S1a, S1(2)
      REAL     S2(2), S3(2), S4(2), Vin, Iin
      REAL     Vout, Iout, Ia, Vprim, Vsec, RT_14
      REAL     RT_15, RT_16, RT_17, RT_18, RT_19
      REAL     RT_20, RT_21, RT_22, RT_23(7)
      REAL     RT_24(7), RT_25(7), RT_26(7)

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD1_2, RVD1_3
      REAL     RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 3
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 67
      IPGB      = NPGB
      NPGB      = NPGB + 11
      INODE     = NNODE + 2
      NNODE     = NNODE + 12
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 26
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      RT_5     = STOF(ISTOF + 5)
      RT_6     = STOF(ISTOF + 6)
      RT_7     = STOF(ISTOF + 7)
      RT_8     = STOF(ISTOF + 8)
      RT_9     = STOF(ISTOF + 9)
      RT_10    = STOF(ISTOF + 10)
      S2a      = STOF(ISTOF + 11)
      IT_1     = STOI(ISTOI + 1)
      RT_11    = STOF(ISTOF + 12)
      RT_12    = STOF(ISTOF + 13)
      RT_13    = STOF(ISTOF + 14)
      S1a      = STOF(ISTOF + 15)
      CLK      = STOI(ISTOI + 2)
      Vin      = STOF(ISTOF + 24)
      Iin      = STOF(ISTOF + 25)
      Vout     = STOF(ISTOF + 26)
      Iout     = STOF(ISTOF + 27)
      Ia       = STOF(ISTOF + 28)
      Vprim    = STOF(ISTOF + 29)
      Vsec     = STOF(ISTOF + 30)
      RT_14    = STOF(ISTOF + 31)
      RT_15    = STOF(ISTOF + 32)
      IT_2     = STOI(ISTOI + 3)
      RT_16    = STOF(ISTOF + 33)
      RT_17    = STOF(ISTOF + 34)
      RT_18    = STOF(ISTOF + 35)
      RT_19    = STOF(ISTOF + 36)
      RT_20    = STOF(ISTOF + 37)
      RT_21    = STOF(ISTOF + 38)
      RT_22    = STOF(ISTOF + 39)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         S1(IT_0) = STOF(ISTOF + 15 + IT_0)
         S2(IT_0) = STOF(ISTOF + 17 + IT_0)
         S3(IT_0) = STOF(ISTOF + 19 + IT_0)
         S4(IT_0) = STOF(ISTOF + 21 + IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         RT_23(IT_0) = STOF(ISTOF + 39 + IT_0)
         RT_24(IT_0) = STOF(ISTOF + 46 + IT_0)
         RT_25(IT_0) = STOF(ISTOF + 53 + IT_0)
         RT_26(IT_0) = STOF(ISTOF + 60 + IT_0)
      END DO

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 110:[const] Real Constant 
      RT_15 = 48.0

! 160:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,352787754)
      CALL E_XSGEN1_EXE(1,200000.0,RVD2_1)
      RT_8 = RVD2_1(1)

! 170:[const] Real Constant 
      RT_3 = 0.5

! 180:[const] Real Constant 
      RT_17 = 0.0

! 190:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,50234200)
      CALL E_XSGEN1_EXE(1,100000.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 200:[const] Real Constant 
      RT_19 = 0.0

! 210:[const] Real Constant 
      RT_5 = 0.5

! 220:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1547727845)
      CALL E_XSGEN1_EXE(1,100000.0,RVD2_1)
      RT_4 = RVD2_1(1)

! 230:[const] Real Constant 
      RT_18 = 0.0

! 240:[const] Real Constant 
      RT_20 = 0.0

! 290:[sumjct] Summing/Differencing Junctions 
      RT_14 = + RT_15 - RT_1

! 300:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_14
      RVD2_1(2) = 0.0
      RT_6 = EMTDC_XPI(0,0.994658,2.95e-005,0.0,20.0,RVD1_1,RVD2_1)

! 310:[sumjct] Summing/Differencing Junctions 
      RT_10 = + RT_6 - RT_16

! 320:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_10
      RVD2_1(2) = 0.0
      RT_7 = EMTDC_XPI(0,3.488,1.48e-005,0.0,3.3,RVD1_1,RVD2_1)

! 330:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_7,RT_8,1.0,0.0,0.0,RVD2_1)
      RT_9 = RVD2_1(1)

! 340:[inv] Interpolated Logic Inverter 
      IF (NINT(RT_9) .NE. 0) THEN
         CLK = 0
      ELSE
         CLK = 1
      ENDIF

! 350:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_3,RT_2,1.0,0.0,0.0,RVD2_1)
      S1a = RVD2_1(1)

! 360:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_5,RT_4,1.0,0.0,0.0,RVD2_1)
      S2a = RVD2_1(1)

! 370:[logic_mult] Multiple Input Logic Gate 
!
! Multi input XOR gate
!
      IF ( (NINT(S1a) .NE. 0) .NEQV. (CLK .NE. 0) ) THEN
        IT_1 = 1
      ELSE
        IT_1 = 0
      ENDIF

! 400:[logic_mult] Multiple Input Logic Gate 
!
! Multi input XOR gate
!
      IF ( (NINT(S2a) .NE. 0) .NEQV. (CLK .NE. 0) ) THEN
        IT_2 = 1
      ELSE
        IT_2 = 0
      ENDIF

! 420:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,REAL(IT_1),RT_20,1.0,0.0,0.0,S4)

! 430:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,S2a,RT_18,1.0,0.0,0.0,S2)

! 440:[pgb] Output Channel 'S4'

      PGB(IPGB+8) = REAL(IT_1)

! 450:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,REAL(IT_2),RT_19,1.0,0.0,0.0,S3)

! 460:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,S1a,RT_17,1.0,0.0,0.0,S1)

! 470:[pgb] Output Channel 'S1'

      PGB(IPGB+9) = S1a

! 480:[pgb] Output Channel 'PIv'

      PGB(IPGB+10) = RT_6

! 490:[pgb] Output Channel 'PIi'

      PGB(IPGB+11) = RT_7

! 500:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,177393987)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+8), NINT(S4(1)), S4(2))

! 510:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1154642816)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+12), NINT(S2(1)), S2(2))

! 520:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,192569840)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+6), NINT(S3(1)), S3(2))

! 530:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,829171649)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+10), NINT(S1(1)), S1(2))

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,424166932)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+14), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,2033003453)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+24), 1, 0.0)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
!  DC source: Type: Ideal
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+5),RVD1_4,0,RVD1_1,RVD1_2,RVD1_&
     &3)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1070072945)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+23), 1, 0.0)

! 1:[xfmr-3w] Single Phase 3 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      CALL TSAT1_EXE( (IBRCH(1)+4),0,0,SS(1),1.0,0)
!

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,639991039)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+20), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,837147495)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+18), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1910112750)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+16), 1, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = RT_5
      STOF(ISTOF + 6) = RT_6
      STOF(ISTOF + 7) = RT_7
      STOF(ISTOF + 8) = RT_8
      STOF(ISTOF + 9) = RT_9
      STOF(ISTOF + 10) = RT_10
      STOF(ISTOF + 11) = S2a
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 12) = RT_11
      STOF(ISTOF + 13) = RT_12
      STOF(ISTOF + 14) = RT_13
      STOF(ISTOF + 15) = S1a
      STOI(ISTOI + 2) = CLK
      STOF(ISTOF + 24) = Vin
      STOF(ISTOF + 25) = Iin
      STOF(ISTOF + 26) = Vout
      STOF(ISTOF + 27) = Iout
      STOF(ISTOF + 28) = Ia
      STOF(ISTOF + 29) = Vprim
      STOF(ISTOF + 30) = Vsec
      STOF(ISTOF + 31) = RT_14
      STOF(ISTOF + 32) = RT_15
      STOI(ISTOI + 3) = IT_2
      STOF(ISTOF + 33) = RT_16
      STOF(ISTOF + 34) = RT_17
      STOF(ISTOF + 35) = RT_18
      STOF(ISTOF + 36) = RT_19
      STOF(ISTOF + 37) = RT_20
      STOF(ISTOF + 38) = RT_21
      STOF(ISTOF + 39) = RT_22

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 15 + IT_0) = S1(IT_0)
         STOF(ISTOF + 17 + IT_0) = S2(IT_0)
         STOF(ISTOF + 19 + IT_0) = S3(IT_0)
         STOF(ISTOF + 21 + IT_0) = S4(IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 39 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 46 + IT_0) = RT_24(IT_0)
         STOF(ISTOF + 53 + IT_0) = RT_25(IT_0)
         STOF(ISTOF + 60 + IT_0) = RT_26(IT_0)
      END DO

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
!     SUBR    FTN180        ! FFT Calculation
      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_2, NT_3, NT_4, NT_6, NT_8
      INTEGER  NT_12

! Control Signals
      REAL     RT_1, RT_11, RT_12, RT_13, Vin
      REAL     Iin, Vout, Iout, Ia, Vprim, Vsec
      REAL     RT_16, RT_21, RT_22, RT_23(7)
      REAL     RT_24(7), RT_25(7), RT_26(7)

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 11
      INODE     = NNODE + 2
      NNODE     = NNODE + 12
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 26
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_11    = STOF(ISTOF + 12)
      RT_12    = STOF(ISTOF + 13)
      RT_13    = STOF(ISTOF + 14)
      Vin      = STOF(ISTOF + 24)
      Iin      = STOF(ISTOF + 25)
      Vout     = STOF(ISTOF + 26)
      Iout     = STOF(ISTOF + 27)
      Ia       = STOF(ISTOF + 28)
      Vprim    = STOF(ISTOF + 29)
      Vsec     = STOF(ISTOF + 30)
      RT_16    = STOF(ISTOF + 33)
      RT_21    = STOF(ISTOF + 38)
      RT_22    = STOF(ISTOF + 39)

! Array (1:7) quantities...
      DO IT_0 = 1,7
         RT_23(IT_0) = STOF(ISTOF + 39 + IT_0)
         RT_24(IT_0) = STOF(ISTOF + 46 + IT_0)
         RT_25(IT_0) = STOF(ISTOF + 53 + IT_0)
         RT_26(IT_0) = STOF(ISTOF + 60 + IT_0)
      END DO

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_6  = NODE(INODE + 6)
      NT_8  = NODE(INODE + 8)
      NT_12 = NODE(INODE + 10)

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[ammeter] Current Meter 'Iin'
      Iin = ( CBR((IBRCH(1)+21), SS(1)))

! 20:[voltmeter] Voltmeter (Line - Line) 'Vsec'
      Vsec = EMTDC_VVDC(SS(1), NT_4, 0)

! 30:[voltmeter] Voltmeter (Line - Line) 'Vin'
      Vin = EMTDC_VVDC(SS(1), NT_6, NT_8)

! 40:[ammeter] Current Meter 'Ia'
      Ia = (-CBR((IBRCH(1)+22), SS(1)))

! 50:[ammeter] Current Meter 'Iout'
      Iout = (-CBR((IBRCH(1)+19), SS(1)))

! 60:[voltmeter] Voltmeter (Line - Line) 'Vprim'
      Vprim = EMTDC_VVDC(SS(1), NT_2, NT_12)

! 70:[voltmeter] Voltmeter (Line - Line) 'Vout'
      Vout = EMTDC_VVDC(SS(1), NT_3, 0)

! 80:[pgb] Output Channel 'Vprim'

      PGB(IPGB+1) = 1000.0 * Vprim

! 90:[pgb] Output Channel 'Ia'

      PGB(IPGB+2) = 1000.0 * Ia

! 100:[pgb] Output Channel 'Vsec'

      PGB(IPGB+3) = 1000.0 * Vsec

! 120:[gain] Gain Block 
!  Gain
      RT_1 = 1000.0 * Vout

! 130:[pgb] Output Channel 'Vout'

      PGB(IPGB+4) = RT_1

! 140:[gain] Gain Block 
!  Gain
      RT_16 = 1000.0 * Iout

! 150:[pgb] Output Channel 'Iout'

      PGB(IPGB+5) = RT_16

! 250:[mult] Multiplier 
      RT_12 = Vout * Iout

! 260:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(1,0,7,1,100.0,100.0,Iin,IVD1_1,RT_23,RT_24,RT_13)
!

! 270:[mult] Multiplier 
      RT_11 = Vin * RT_13

! 280:[pgb] Output Channel 'Iin'

      PGB(IPGB+6) = 1000.0 * RT_13

! 380:[div] Divider 
!
      IF (ABS(RT_11) .LT. 1.0E-10) THEN
         IF (RT_11 .LT. 0.0)  THEN
            RT_21 = -1.0E10 * RT_12
         ELSE
            RT_21 =  1.0E10 * RT_12
         ENDIF
      ELSE
         RT_21 = RT_12 / RT_11
      ENDIF
!

! 390:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(1,0,7,1,100.0,100.0,RT_21,IVD1_1,RT_25,RT_26,RT_22)
!

! 410:[pgb] Output Channel 'Eficiência'

      PGB(IPGB+7) = RT_22

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 12) = RT_11
      STOF(ISTOF + 13) = RT_12
      STOF(ISTOF + 14) = RT_13
      STOF(ISTOF + 24) = Vin
      STOF(ISTOF + 25) = Iin
      STOF(ISTOF + 26) = Vout
      STOF(ISTOF + 27) = Iout
      STOF(ISTOF + 28) = Ia
      STOF(ISTOF + 29) = Vprim
      STOF(ISTOF + 30) = Vsec
      STOF(ISTOF + 33) = RT_16
      STOF(ISTOF + 38) = RT_21
      STOF(ISTOF + 39) = RT_22

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 39 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 46 + IT_0) = RT_24(IT_0)
         STOF(ISTOF + 53 + IT_0) = RT_25(IT_0)
         STOF(ISTOF + 60 + IT_0) = RT_26(IT_0)
      END DO

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_5, RT_15, RT_17, RT_18
      REAL     RT_19, RT_20

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 12
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 26
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 110:[const] Real Constant 

! 160:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,352787754)
      CALL E_XSGEN1_CFG(1,0.0,100.0,3.3,0.0)

! 170:[const] Real Constant 

! 180:[const] Real Constant 

! 190:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,50234200)
      CALL E_XSGEN1_CFG(1,0.0,0.0,1.0,0.0)

! 200:[const] Real Constant 

! 210:[const] Real Constant 

! 220:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1547727845)
      CALL E_XSGEN1_CFG(1,180.0,0.0,1.0,0.0)

! 230:[const] Real Constant 

! 240:[const] Real Constant 

! 290:[sumjct] Summing/Differencing Junctions 

! 300:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 310:[sumjct] Summing/Differencing Junctions 

! 320:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 330:[compar] Two Input Comparator 

! 340:[inv] Interpolated Logic Inverter 

! 350:[compar] Two Input Comparator 

! 360:[compar] Two Input Comparator 

! 420:[compar] Two Input Comparator 

! 430:[compar] Two Input Comparator 

! 440:[pgb] Output Channel 'S4'

! 450:[compar] Two Input Comparator 

! 460:[compar] Two Input Comparator 

! 470:[pgb] Output Channel 'S1'

! 480:[pgb] Output Channel 'PIv'

! 490:[pgb] Output Channel 'PIi'

! 500:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+9),SS(1),1,0,1,5000.0,0.0,0.05)

! 510:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+13),SS(1),1,0,1,5000.0,0.0,0.05)

! 520:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+7),SS(1),1,0,1,5000.0,0.0,0.05)

! 530:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+11),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+15),SS(1),1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_1PVSRC_CFG(0,0,6,0.4,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[xfmr-3w] Single Phase 3 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,1690817836)
      CALL E_TF3W_CFG((IXFMR + 1),1,100.0,100000.0,1.0e-007,1.0e-007,1.0&
     &e-007,0.0,0.4,0.06,0.06,0.4)
      IF (0.0 .LT. 0.001) THEN
        RVD1_1 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_4 = 0.0
        RVD1_1 = 3.0/(100.0*RVD1_4)
        IVD1_1 = 1
      ENDIF
      RVD1_2 = RVD1_1*0.4*0.4
      RVD1_3 = RVD1_1*0.06*0.06
      RVD1_4 = RVD1_1*0.06*0.06
      CALL E_BRANCH_CFG( (IBRCH(1)+1),SS(1),IVD1_1,0,0,RVD1_2,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+2),SS(1),IVD1_1,0,0,RVD1_3,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+3),SS(1),IVD1_1,0,0,RVD1_4,0.0,0.0)
      CALL TSAT1_CFG( (IBRCH(1)+4),0,0,SS(1),100.0,0.4,0.2,1.17,100000.0&
     &,0.0,0.4,0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+17),SS(1),1,0,1,5000.0,0.0,0.05)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_2, NT_3, NT_4, NT_6, NT_8
      INTEGER  NT_12

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 12
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 26
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_6  = NODE(INODE + 6)
      NT_8  = NODE(INODE + 8)
      NT_12 = NODE(INODE + 10)

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 80:[pgb] Output Channel 'Vprim'

! 90:[pgb] Output Channel 'Ia'

! 100:[pgb] Output Channel 'Vsec'

! 120:[gain] Gain Block 

! 130:[pgb] Output Channel 'Vout'

! 140:[gain] Gain Block 

! 150:[pgb] Output Channel 'Iout'

! 250:[mult] Multiplier 

! 260:[fft] On-Line Frequency Scanner 

! 270:[mult] Multiplier 

! 280:[pgb] Output Channel 'Iin'

! 380:[div] Divider 

! 390:[fft] On-Line Frequency Scanner 

! 410:[pgb] Output Channel 'Eficiência'

      RETURN
      END

