!=======================================================================
! Generated by  : PSCAD v4.5.0.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  S2a, S1a, IT_1, IT_2, CLK
      REAL     RT_1, RT_2, RT_3, RT_4, Iin, RT_5
      REAL     RT_6, RT_7, Vin, Vout, Iout, Ia
      REAL     Vprim, S1(2), S2(2), S3(2), S4(2)
      REAL     I_out, Vsec, RT_8, RT_9, RT_10
      REAL     RT_11(7), RT_12(7), RT_13(7)
      REAL     RT_14(7), RT_15, RT_16, RT_17
      REAL     RT_18, RT_19, RT_20, RT_21

! Internal Variables
      REAL     RVD2_1(2), RVD1_1, RVD1_2, RVD1_3
      REAL     RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 5
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 61
      IPGB      = NPGB
      NPGB      = NPGB + 16
      INODE     = NNODE + 2
      NNODE     = NNODE + 13
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 27
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      Iin      = STOF(ISTOF + 5)
      RT_5     = STOF(ISTOF + 6)
      RT_6     = STOF(ISTOF + 7)
      RT_7     = STOF(ISTOF + 8)
      S2a      = STOI(ISTOI + 1)
      S1a      = STOI(ISTOI + 2)
      IT_1     = STOI(ISTOI + 3)
      IT_2     = STOI(ISTOI + 4)
      Vin      = STOF(ISTOF + 9)
      Vout     = STOF(ISTOF + 10)
      Iout     = STOF(ISTOF + 11)
      Ia       = STOF(ISTOF + 12)
      Vprim    = STOF(ISTOF + 13)
      CLK      = STOI(ISTOI + 5)
      I_out    = STOF(ISTOF + 22)
      Vsec     = STOF(ISTOF + 23)
      RT_8     = STOF(ISTOF + 24)
      RT_9     = STOF(ISTOF + 25)
      RT_10    = STOF(ISTOF + 26)
      RT_15    = STOF(ISTOF + 55)
      RT_16    = STOF(ISTOF + 56)
      RT_17    = STOF(ISTOF + 57)
      RT_18    = STOF(ISTOF + 58)
      RT_19    = STOF(ISTOF + 59)
      RT_20    = STOF(ISTOF + 60)
      RT_21    = STOF(ISTOF + 61)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         S1(IT_0) = STOF(ISTOF + 13 + IT_0)
         S2(IT_0) = STOF(ISTOF + 15 + IT_0)
         S3(IT_0) = STOF(ISTOF + 17 + IT_0)
         S4(IT_0) = STOF(ISTOF + 19 + IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         RT_11(IT_0) = STOF(ISTOF + 26 + IT_0)
         RT_12(IT_0) = STOF(ISTOF + 33 + IT_0)
         RT_13(IT_0) = STOF(ISTOF + 40 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 47 + IT_0)
      END DO

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 100:[const] Real Constant 
      RT_7 = 54.0

! 130:[Untitled_3]  
        CALL OUT_CONTROL_HBRIDGE(Vout, Iout, RT_5, RT_6, RT_7)

! 140:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,352787754)
      CALL E_XSGEN1_EXE(1,200000.0,RVD2_1)
      RT_1 = RVD2_1(1)

! 150:[const] Real Constant 
      RT_15 = 0.5

! 170:[const] Real Constant 
      RT_18 = 0.0

! 180:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1819855898)
      CALL E_XSGEN1_EXE(1,100000.0,RVD2_1)
      RT_16 = RVD2_1(1)

! 190:[const] Real Constant 
      RT_20 = 0.0

! 200:[const] Real Constant 
      RT_17 = 0.5

! 210:[const] Real Constant 
      RT_19 = 0.0

! 220:[const] Real Constant 
      RT_21 = 0.0

! 270:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_6,RT_1,1.0,0.0,0.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 280:[inv] Interpolated Logic Inverter 
      IF (NINT(RT_2) .NE. 0) THEN
         CLK = 0
      ELSE
         CLK = 1
      ENDIF

! 290:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_15,RT_16,1.0,0.0,0.0,RVD2_1)
      S1a = NINT(RVD2_1(1))

! 300:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_16,RT_17,1.0,0.0,0.0,RVD2_1)
      S2a = NINT(RVD2_1(1))

! 310:[logic_mult] Multiple Input Logic Gate 
!
! Multi input XOR gate
!
      IF ( (S1a .NE. 0) .NEQV. (CLK .NE. 0) ) THEN
        IT_2 = 1
      ELSE
        IT_2 = 0
      ENDIF

! 340:[logic_mult] Multiple Input Logic Gate 
!
! Multi input XOR gate
!
      IF ( (S2a .NE. 0) .NEQV. (CLK .NE. 0) ) THEN
        IT_1 = 1
      ELSE
        IT_1 = 0
      ENDIF

! 360:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,REAL(IT_2),RT_21,1.0,0.0,0.0,S4)

! 370:[pgb] Output Channel 'S4'

      PGB(IPGB+7) = REAL(IT_2)

! 380:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,REAL(S2a),RT_19,1.0,0.0,0.0,S2)

! 390:[pgb] Output Channel 'S2'

      PGB(IPGB+8) = REAL(S2a)

! 400:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,REAL(IT_1),RT_20,1.0,0.0,0.0,S3)

! 410:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(1,0,REAL(S1a),RT_18,1.0,0.0,0.0,S1)

! 420:[pgb] Output Channel 'S3'

      PGB(IPGB+9) = REAL(IT_1)

! 430:[pgb] Output Channel 'S1'

      PGB(IPGB+10) = REAL(S1a)

! 440:[pgb] Output Channel 'CLK'

      PGB(IPGB+11) = REAL(CLK)

! 450:[pgb] Output Channel 'PIi'

      PGB(IPGB+12) = RT_6

! 460:[pgb] Output Channel 'PIv'

      PGB(IPGB+13) = RT_5

! 470:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,621349459)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+15), NINT(S4(1)), S4(2))

! 480:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1162842563)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+17), NINT(S2(1)), S2(2))

! 490:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,9668441)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+13), NINT(S3(1)), S3(2))

! 500:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1360045241)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+11), NINT(S1(1)), S1(2))

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,970214989)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+23), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1572077796)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+19), 1, 0.0)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
!  DC source: Type: Ideal
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+5),RVD1_4,0,RVD1_1,RVD1_2,RVD1_&
     &3)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1041119457)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+24), 1, 0.0)

! 1:[xfmr-3w] Single Phase 3 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      CALL TSAT1_EXE( (IBRCH(1)+4),0,0,SS(1),1.0,0)
!

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
!  Single Phase AC source: Type: Ideal
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF = NRTCF + 4
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+10),RVD1_4,1,RVD1_1,RVD1_2,RVD1&
     &_3)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1660814708)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+26), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,728736724)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+25), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,683206823)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+21), 1, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = Iin
      STOF(ISTOF + 6) = RT_5
      STOF(ISTOF + 7) = RT_6
      STOF(ISTOF + 8) = RT_7
      STOI(ISTOI + 1) = S2a
      STOI(ISTOI + 2) = S1a
      STOI(ISTOI + 3) = IT_1
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 9) = Vin
      STOF(ISTOF + 10) = Vout
      STOF(ISTOF + 11) = Iout
      STOF(ISTOF + 12) = Ia
      STOF(ISTOF + 13) = Vprim
      STOI(ISTOI + 5) = CLK
      STOF(ISTOF + 22) = I_out
      STOF(ISTOF + 23) = Vsec
      STOF(ISTOF + 24) = RT_8
      STOF(ISTOF + 25) = RT_9
      STOF(ISTOF + 26) = RT_10
      STOF(ISTOF + 55) = RT_15
      STOF(ISTOF + 56) = RT_16
      STOF(ISTOF + 57) = RT_17
      STOF(ISTOF + 58) = RT_18
      STOF(ISTOF + 59) = RT_19
      STOF(ISTOF + 60) = RT_20
      STOF(ISTOF + 61) = RT_21

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 13 + IT_0) = S1(IT_0)
         STOF(ISTOF + 15 + IT_0) = S2(IT_0)
         STOF(ISTOF + 17 + IT_0) = S3(IT_0)
         STOF(ISTOF + 19 + IT_0) = S4(IT_0)
      END DO

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 26 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 33 + IT_0) = RT_12(IT_0)
         STOF(ISTOF + 40 + IT_0) = RT_13(IT_0)
         STOF(ISTOF + 47 + IT_0) = RT_14(IT_0)
      END DO

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
!     SUBR    FTN180        ! FFT Calculation
      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_2, NT_3, NT_4, NT_5, NT_7
      INTEGER  NT_13

! Control Signals
      REAL     RT_3, RT_4, Iin, Vin, Vout, Iout
      REAL     Ia, Vprim, I_out, Vsec, RT_8, RT_9
      REAL     RT_10, RT_11(7), RT_12(7)
      REAL     RT_13(7), RT_14(7)

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 16
      INODE     = NNODE + 2
      NNODE     = NNODE + 13
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 27
!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      Iin      = STOF(ISTOF + 5)
      Vin      = STOF(ISTOF + 9)
      Vout     = STOF(ISTOF + 10)
      Iout     = STOF(ISTOF + 11)
      Ia       = STOF(ISTOF + 12)
      Vprim    = STOF(ISTOF + 13)
      I_out    = STOF(ISTOF + 22)
      Vsec     = STOF(ISTOF + 23)
      RT_8     = STOF(ISTOF + 24)
      RT_9     = STOF(ISTOF + 25)
      RT_10    = STOF(ISTOF + 26)

! Array (1:7) quantities...
      DO IT_0 = 1,7
         RT_11(IT_0) = STOF(ISTOF + 26 + IT_0)
         RT_12(IT_0) = STOF(ISTOF + 33 + IT_0)
         RT_13(IT_0) = STOF(ISTOF + 40 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 47 + IT_0)
      END DO

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_5  = NODE(INODE + 5)
      NT_7  = NODE(INODE + 7)
      NT_13 = NODE(INODE + 11)

!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[ammeter] Current Meter 'Iin'
      Iin = ( CBR((IBRCH(1)+8), SS(1)))

! 20:[voltmeter] Voltmeter (Line - Line) 'Vsec'
      Vsec = EMTDC_VVDC(SS(1), NT_5, 0)

! 30:[voltmeter] Voltmeter (Line - Line) 'Vin'
      Vin = EMTDC_VVDC(SS(1), NT_7, NT_3)

! 40:[ammeter] Current Meter 'Ia'
      Ia = ( CBR((IBRCH(1)+9), SS(1)))

! 50:[ammeter] Current Meter 'Iout'
      Iout = (-CBR((IBRCH(1)+7), SS(1)))

! 60:[voltmeter] Voltmeter (Line - Line) 'Vprim'
      Vprim = EMTDC_VVDC(SS(1), NT_2, NT_13)

! 70:[ammeter] Current Meter 'I_out'
      I_out = ( CBR((IBRCH(1)+6), SS(1)))

! 80:[voltmeter] Voltmeter (Line - Line) 'Vout'
      Vout = EMTDC_VVDC(SS(1), NT_4, 0)

! 90:[pgb] Output Channel 'Vout'

      PGB(IPGB+1) = 1000.0 * Vout

! 110:[pgb] Output Channel 'Iout'

      PGB(IPGB+2) = 1000.0 * I_out

! 120:[pgb] Output Channel 'Iout'

      PGB(IPGB+3) = 1000.0 * Iout

! 160:[pgb] Output Channel 'Vsec'

      PGB(IPGB+4) = 1000.0 * Vsec

! 230:[mult] Multiplier 
      RT_4 = Vout * Iout

! 240:[mult] Multiplier 
      RT_8 = Vin * Iin

! 250:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(1,0,7,1,100.0,100.0,RT_8,IVD1_1,RT_11,RT_12,RT_3)
!

! 260:[pgb] Output Channel 'Iin'

      PGB(IPGB+5) = 1000.0 * Iin

! 320:[div] Divider 
!
      IF (ABS(RT_3) .LT. 1.0E-10) THEN
         IF (RT_3 .LT. 0.0)  THEN
            RT_9 = -1.0E10 * RT_4
         ELSE
            RT_9 =  1.0E10 * RT_4
         ENDIF
      ELSE
         RT_9 = RT_4 / RT_3
      ENDIF
!

! 330:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL FTN180(1,0,7,1,100.0,100.0,RT_9,IVD1_1,RT_13,RT_14,RT_10)
!

! 350:[pgb] Output Channel 'Eficiência'

      PGB(IPGB+6) = RT_10

! 510:[pgb] Output Channel 'Ia'

      PGB(IPGB+14) = 1000.0 * Ia

! 520:[pgb] Output Channel 'Vsec'

      PGB(IPGB+15) = 1000.0 * Vsec

! 530:[pgb] Output Channel 'Vprim'

      PGB(IPGB+16) = 1000.0 * Vprim

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = Iin
      STOF(ISTOF + 9) = Vin
      STOF(ISTOF + 10) = Vout
      STOF(ISTOF + 11) = Iout
      STOF(ISTOF + 12) = Ia
      STOF(ISTOF + 13) = Vprim
      STOF(ISTOF + 22) = I_out
      STOF(ISTOF + 23) = Vsec
      STOF(ISTOF + 24) = RT_8
      STOF(ISTOF + 25) = RT_9
      STOF(ISTOF + 26) = RT_10

! Array (1:7) quantities...
      DO IT_0 = 1,7
         STOF(ISTOF + 26 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 33 + IT_0) = RT_12(IT_0)
         STOF(ISTOF + 40 + IT_0) = RT_13(IT_0)
         STOF(ISTOF + 47 + IT_0) = RT_14(IT_0)
      END DO

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_7, RT_15, RT_17, RT_18, RT_19
      REAL     RT_20, RT_21

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 13
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 27
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 100:[const] Real Constant 

! 130:[Untitled_3]  

! 140:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,352787754)
      CALL E_XSGEN1_CFG(1,0.0,100.0,3.3,0.0)

! 150:[const] Real Constant 

! 170:[const] Real Constant 

! 180:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,1819855898)
      CALL E_XSGEN1_CFG(1,0.0,0.0,1.0,0.0)

! 190:[const] Real Constant 

! 200:[const] Real Constant 

! 210:[const] Real Constant 

! 220:[const] Real Constant 

! 270:[compar] Two Input Comparator 

! 280:[inv] Interpolated Logic Inverter 

! 290:[compar] Two Input Comparator 

! 300:[compar] Two Input Comparator 

! 360:[compar] Two Input Comparator 

! 370:[pgb] Output Channel 'S4'

! 380:[compar] Two Input Comparator 

! 390:[pgb] Output Channel 'S2'

! 400:[compar] Two Input Comparator 

! 410:[compar] Two Input Comparator 

! 420:[pgb] Output Channel 'S3'

! 430:[pgb] Output Channel 'S1'

! 440:[pgb] Output Channel 'CLK'

! 450:[pgb] Output Channel 'PIi'

! 460:[pgb] Output Channel 'PIv'

! 470:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0.&
     &0)
      CALL E_BRANCH_CFG( (IBRCH(1)+16),SS(1),1,0,1,5.0e+012,0.0,0.05)

! 480:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0.&
     &0)
      CALL E_BRANCH_CFG( (IBRCH(1)+18),SS(1),1,0,1,5.0e+012,0.0,0.05)

! 490:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0.&
     &0)
      CALL E_BRANCH_CFG( (IBRCH(1)+14),SS(1),1,0,1,5.0e+012,0.0,0.05)

! 500:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0.&
     &0)
      CALL E_BRANCH_CFG( (IBRCH(1)+12),SS(1),1,0,1,5.0e+012,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0&
     &.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0&
     &.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+20),SS(1),1,0,1,5.0e+012,0.0,0.05)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_1PVSRC_CFG(0,0,6,0.4,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0&
     &.0)

! 1:[xfmr-3w] Single Phase 3 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,1310622075)
      CALL E_TF3W_CFG((IXFMR + 1),1,100.0,100000.0,1.0e-006,1.0e-006,1.0&
     &e-006,0.0,0.4,0.08,0.08,0.4)
      IF (0.0 .LT. 0.001) THEN
        RVD1_1 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_4 = 0.0
        RVD1_1 = 3.0/(100.0*RVD1_4)
        IVD1_1 = 1
      ENDIF
      RVD1_2 = RVD1_1*0.4*0.4
      RVD1_3 = RVD1_1*0.08*0.08
      RVD1_4 = RVD1_1*0.08*0.08
      CALL E_BRANCH_CFG( (IBRCH(1)+1),SS(1),IVD1_1,0,0,RVD1_2,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+2),SS(1),IVD1_1,0,0,RVD1_3,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+3),SS(1),IVD1_1,0,0,RVD1_4,0.0,0.0)
      CALL TSAT1_CFG( (IBRCH(1)+4),0,0,SS(1),100.0,0.4,0.2,1.17,100000.0&
     &,0.0,0.4,0.0)

! 1:[source_1] Single Phase Voltage Source Model 2 'Source1'
      CALL E_1PVSRC_CFG(1,0,6,0.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0&
     &.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0&
     &.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1.0e+012, 1.0e+012, 1.0e+012, 0.0, 0&
     &.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+22),SS(1),1,0,1,5.0e+012,0.0,0.05)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------


!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_2, NT_3, NT_4, NT_5, NT_7
      INTEGER  NT_13

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 13
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 1

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 27
!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)
      NT_4  = NODE(INODE + 4)
      NT_5  = NODE(INODE + 5)
      NT_7  = NODE(INODE + 7)
      NT_13 = NODE(INODE + 11)

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 90:[pgb] Output Channel 'Vout'

! 110:[pgb] Output Channel 'Iout'

! 120:[pgb] Output Channel 'Iout'

! 160:[pgb] Output Channel 'Vsec'

! 230:[mult] Multiplier 

! 240:[mult] Multiplier 

! 250:[fft] On-Line Frequency Scanner 

! 260:[pgb] Output Channel 'Iin'

! 320:[div] Divider 

! 330:[fft] On-Line Frequency Scanner 

! 350:[pgb] Output Channel 'Eficiência'

! 510:[pgb] Output Channel 'Ia'

! 520:[pgb] Output Channel 'Vsec'

! 530:[pgb] Output Channel 'Vprim'

      RETURN
      END

